jsonl_path: "generation/data/commitpackft_python_cleaned.jsonl"  # 数据集路径
field_name: "code"  # 需要处理的字段名
data_format: "plain"  # 数据格式，可根据实际情况调整
random_seed: 42  # 随机种子，可选
filter_settings:   # 过滤相关设置，可选
  max_modify_lines: 70
  max_hunk_num: 7
  max_samples_total: 10000
  refit: false